## Numpy array basics

In [1]:
import numpy as np

## creating arrays

In [2]:
import numpy as np

In [3]:
zeroes = np.ones((3, 4))
print(zeroes)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## list vs numpy array

In [5]:
py_list = [1,2,3]
print("python list multiplication:" , py_list * 2)

np_array = np.array([1,2,3])
print("numpy array multiplication", np_array * 2)

python list multiplication: [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]
